timeout = 80
timeout_incomplete = 500
prevent_wake = 1
secret = "+coPhKlHE9+oVQCsOeslHA"
# logfile = "/Users/jamestucker/.talon/draconity.log"

[[pipe]]
path = "/Users/jamestucker/.talon/.sys/draconity.sock"

# [[socket]]
# host = "127.0.0.1"
# port = 38065

# [[remote]]
# host = "127.0.0.1"
# port = 38065
